### ISSUE TITLE
Facing problem in running the project

### ISSUE THREAD

**Issue by devyani735** [gowthamraj198/Lighthouse#2] opened 2020-06-17 14:30 UTC
Hi,

When I m running npm run test, it showing the error 'Syntax error: Unexpected token import'.
For more details, attached screenshot.

Can you please help in this. 
![ErrorInProject](https://user-images.githubusercontent.com/67060148/84910936-22683a00-b0d5-11ea-9993-c8d39bad2dab.png)

Thanks in advance.
Devyani

**Comment by gowthamraj198** [comment] 2020-06-17 15:09
Have you installed mochaawesome?
npm i -g mochawesome

**Comment by devyani735** [comment] 2020-06-18 05:04
Hi, 

Yes I installed mocha awesome. Now I got another error. 

URL is not defined. 

Thanks!

**Comment by gowthamraj198** [comment] 2020-06-18 05:28
share the screenshot and error in detail

**Comment by devyani735** [comment] 2020-06-18 05:39
![URLUndefined](https://user-images.githubusercontent.com/67060148/84982314-0f487f00-b154-11ea-9308-72b3ed13824c.png)

**Comment by gowthamraj198** [comment] 2020-06-18 06:46
this one is not related to my repo. you are trying to run lighthouse cli. check lighthouse repo - https://github.com/GoogleChrome/lighthouse

**Comment by devyani735** [comment] 2020-06-18 07:50
Sorry for wrong screenshot, please find the attached screenshot for npm run test.
![ErrorForURL](https://user-images.githubusercontent.com/67060148/84993098-71aa7b00-b166-11ea-92ca-14e986f92593.png)

Thanks for your quick reply.

**Comment by gowthamraj198** [comment] 2020-06-18 09:10
What is your node version? lighthouse requires node version >10. 
https://github.com/GoogleChrome/lighthouse/issues/8909

**Comment by devyani735** [comment] 2020-06-18 09:39
npm version is 5.6.0.

**Comment by gowthamraj198** [comment] 2020-06-18 09:41
check the node version not npm. node version should be >10.

**Comment by devyani735** [comment] 2020-06-18 11:02
Hey @gowthamraj198 ,

It's working now Thanks :) , but I m checking manual as well there is little bit difference in automation and manual report.

Please verify the attached screenshot 
![AutomationReport](https://user-images.githubusercontent.com/67060148/85012874-50a35380-b181-11ea-813e-003ea9381a6c.png)
![ManualReport](https://user-images.githubusercontent.com/67060148/85012875-526d1700-b181-11ea-806b-be21b8138e2f.png)

**Comment by gowthamraj198** [comment] 2020-06-18 11:27
when you run any analysis, run more than once and take the average. this difference is okay.

**Comment by devyani735** [comment] 2020-06-18 14:46
Hi @gowthamraj198 ,

Command line we got the number like accessibility 59, can we print the accessibility data as well same as manual ?
![AutomationREportwebsite](https://user-images.githubusercontent.com/67060148/85035159-83107900-b1a0-11ea-83be-865ca1c3d388.png)
![ManualReportDetail](https://user-images.githubusercontent.com/67060148/85035208-8c014a80-b1a0-11ea-964f-4d36e5dfcb12.png)



For more understanding I attached screenshots.

Thanks in advance.
Devyani

**Comment by gowthamraj198** [comment] 2020-06-19 01:38
as i already mentioned, the number may not same everytime. run more than once and consider the average

**Comment by devyani735** [comment] 2020-06-19 05:26
Hi @gowthamraj198 ,

I am not talking about numbers, In manual we can click on numbers and it's display the description.

Can we do it in automation script.

Thanks!

**Comment by gowthamraj198** [comment] 2020-06-19 05:41
reports should be generated in reports folder. you can do this in report

**Comment by devyani735** [comment] 2020-06-19 06:33
Yes I got that report as well. We are doing for one URL, Can we do it for whole website URL through automation.

**Comment by gowthamraj198** [comment] 2020-06-19 06:49
check the code. it reads the url from a data file. You can do it by changing the data file

**Comment by devyani735** [comment] 2020-06-19 07:21
Thank you so much for your time, I will do and let you know for further help.

Appreciated for your reply. @gowthamraj198

**Comment by gowthamraj198** [comment] 2020-06-19 07:31
closing this issue as the issue is resolved.

**Closed by gowthamraj198** 2020-06-19 07:31 UTC
